version: '2.2'
services:
  cassandra1:
    container_name: cassandra_1
    #command : cqlsh -f data/init.cql
    image: cassandra:latest
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
    volumes:
      - ./db-data:/var/lib/cassandra
      - ./data:/data


  cassandra2:
    container_name: cassandra_2
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    image: cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra_1
      - CASSANDRA_PASSWORD=password123

  fastAPI:
    container_name: fastAPI
    build : .
    image: myimage:latest
    ports:
      - '8000:8000'
